export type LeadStatus =
  | "Ikke kontaktet"
  | "Kontaktet"
  | "Kontaktet - ikke svar"
  | "Booket møte"
  | "Avslått"
  | "Kunde";

export interface Company {
  id: string;
  name: string;
  orgNumber: string;
  contactPerson: string;
  phone: string;
  email: string;
  industry: string;
  city: string;
  address: string;
  revenue: number;
  employees: number;
  lat: number;
  lng: number;
}

export interface Lead extends Company {
  status: LeadStatus;
  lastContacted: string | null;
  assignedTo: string;
  assignedAvatar: string;
  notes: string;
  addedDate: string;
}

export interface Notification {
  id: string;
  company: string;
  message: string;
  date: string;
  type: "follow-up" | "reminder" | "meeting";
  done: boolean;
}

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Bergheim Regnskap AS",
    orgNumber: "912345678",
    contactPerson: "Anders Bergheim",
    phone: "+47 22 33 44 55",
    email: "post@bergheim-regnskap.no",
    industry: "Regnskap",
    city: "Oslo",
    address: "Storgata 12, 0155 Oslo",
    revenue: 8500000,
    employees: 12,
    lat: 59.9139,
    lng: 10.7522,
  },
  {
    id: "2",
    name: "Oslo Frisørsalong",
    orgNumber: "923456789",
    contactPerson: "Maria Andersen",
    phone: "+47 22 44 55 66",
    email: "post@oslo-frisor.no",
    industry: "Frisør",
    city: "Oslo",
    address: "Karl Johans gate 33, 0162 Oslo",
    revenue: 2200000,
    employees: 5,
    lat: 59.9122,
    lng: 10.7461,
  },
  {
    id: "3",
    name: "Nordvik Bygg AS",
    orgNumber: "934567890",
    contactPerson: "Erik Nordvik",
    phone: "+47 55 66 77 88",
    email: "erik@nordvik-bygg.no",
    industry: "Bygg",
    city: "Bergen",
    address: "Bryggen 5, 5003 Bergen",
    revenue: 15600000,
    employees: 28,
    lat: 60.3913,
    lng: 5.3221,
  },
  {
    id: "4",
    name: "Trondheim IT Konsulent AS",
    orgNumber: "945678901",
    contactPerson: "Kari Thorsen",
    phone: "+47 73 88 99 00",
    email: "kari@trondheim-it.no",
    industry: "IT og teknologi",
    city: "Trondheim",
    address: "Nedre Elvehavn 4, 7042 Trondheim",
    revenue: 12300000,
    employees: 18,
    lat: 63.4305,
    lng: 10.3951,
  },
  {
    id: "5",
    name: "Stavanger Eiendom AS",
    orgNumber: "956789012",
    contactPerson: "Ole Stavanger",
    phone: "+47 51 77 88 99",
    email: "ole@stavanger-eiendom.no",
    industry: "Eiendom",
    city: "Stavanger",
    address: "Øvre Holmegate 15, 4006 Stavanger",
    revenue: 45000000,
    employees: 35,
    lat: 58.9699,
    lng: 5.7331,
  },
  {
    id: "6",
    name: "Molde Transport AS",
    orgNumber: "967890123",
    contactPerson: "Per Molde",
    phone: "+47 71 22 33 44",
    email: "per@molde-transport.no",
    industry: "Transport og logistikk",
    city: "Molde",
    address: "Havnegata 8, 6400 Molde",
    revenue: 9800000,
    employees: 22,
    lat: 62.7375,
    lng: 7.1591,
  },
  {
    id: "7",
    name: "Hansen & Co Advokater",
    orgNumber: "978901234",
    contactPerson: "Ingrid Hansen",
    phone: "+47 22 11 22 33",
    email: "ingrid@hansen-advokater.no",
    industry: "Juridiske tjenester",
    city: "Oslo",
    address: "Munkedamsveien 45, 0250 Oslo",
    revenue: 22000000,
    employees: 15,
    lat: 59.9156,
    lng: 10.7202,
  },
  {
    id: "8",
    name: "Bergen Elektro AS",
    orgNumber: "989012345",
    contactPerson: "Bjørn Larsen",
    phone: "+47 55 33 44 55",
    email: "bjorn@bergen-elektro.no",
    industry: "Elektro",
    city: "Bergen",
    address: "Møllendalsveien 12, 5009 Bergen",
    revenue: 18700000,
    employees: 31,
    lat: 60.3745,
    lng: 5.3472,
  },
  {
    id: "9",
    name: "Sunnmøre Fisk AS",
    orgNumber: "990123456",
    contactPerson: "Tor Olsen",
    phone: "+47 70 12 23 34",
    email: "tor@sunmore-fisk.no",
    industry: "Fiskeri og havbruk",
    city: "Ålesund",
    address: "Skansekaia 3, 6002 Ålesund",
    revenue: 67000000,
    employees: 55,
    lat: 62.4722,
    lng: 6.1496,
  },
  {
    id: "10",
    name: "Kristiansen Reklamebyrå",
    orgNumber: "901234567",
    contactPerson: "Lise Kristiansen",
    phone: "+47 22 99 00 11",
    email: "lise@kristiansen-reklame.no",
    industry: "Markedsføring",
    city: "Oslo",
    address: "Youngstorget 3, 0181 Oslo",
    revenue: 5400000,
    employees: 9,
    lat: 59.9168,
    lng: 10.7516,
  },
  {
    id: "11",
    name: "TechStart Bergen",
    orgNumber: "912111222",
    contactPerson: "Silje Bakke",
    phone: "+47 55 88 77 66",
    email: "silje@techstart.no",
    industry: "IT og teknologi",
    city: "Bergen",
    address: "Vaskerelven 39, 5014 Bergen",
    revenue: 3200000,
    employees: 7,
    lat: 60.3886,
    lng: 5.3323,
  },
  {
    id: "12",
    name: "Byggmester Halvorsen AS",
    orgNumber: "923222333",
    contactPerson: "Geir Halvorsen",
    phone: "+47 22 66 55 44",
    email: "geir@halvorsen-bygg.no",
    industry: "Bygg",
    city: "Oslo",
    address: "Industrigata 22, 0357 Oslo",
    revenue: 31000000,
    employees: 45,
    lat: 59.9295,
    lng: 10.7178,
  },
  {
    id: "13",
    name: "Trøndertaxi AS",
    orgNumber: "934333444",
    contactPerson: "Lars Pedersen",
    phone: "+47 73 00 11 22",
    email: "lars@trondertaxi.no",
    industry: "Transport og logistikk",
    city: "Trondheim",
    address: "Bøndernes Hus, 7010 Trondheim",
    revenue: 14500000,
    employees: 38,
    lat: 63.4159,
    lng: 10.4076,
  },
  {
    id: "14",
    name: "Vestlandet Helse AS",
    orgNumber: "945444555",
    contactPerson: "Anne Fjeld",
    phone: "+47 55 44 33 22",
    email: "anne@vestlandet-helse.no",
    industry: "Helse og omsorg",
    city: "Bergen",
    address: "Sandviksboder 1, 5035 Bergen",
    revenue: 7800000,
    employees: 24,
    lat: 60.4025,
    lng: 5.3198,
  },
  {
    id: "15",
    name: "Sørlandets Catering",
    orgNumber: "956555666",
    contactPerson: "Thomas Nilsen",
    phone: "+47 38 11 22 33",
    email: "thomas@sorlandets-catering.no",
    industry: "Matservering",
    city: "Kristiansand",
    address: "Posebyen 7, 4611 Kristiansand",
    revenue: 4100000,
    employees: 14,
    lat: 58.1467,
    lng: 7.9956,
  },
];

export const mockLeads: Lead[] = [
  {
    ...mockCompanies[0],
    status: "Kontaktet",
    lastContacted: "2024-01-15",
    assignedTo: "Ola Nordmann",
    assignedAvatar: "ON",
    notes: "Interessert i automatisering av regnskapsrapporter. Ring tilbake mandag.",
    addedDate: "2024-01-10",
  },
  {
    ...mockCompanies[2],
    status: "Booket møte",
    lastContacted: "2024-01-18",
    assignedTo: "Kari Hansen",
    assignedAvatar: "KH",
    notes: "Møte satt til 25. januar kl 10:00. Fokus på prosjektledelse.",
    addedDate: "2024-01-08",
  },
  {
    ...mockCompanies[4],
    status: "Kunde",
    lastContacted: "2024-01-20",
    assignedTo: "Ola Nordmann",
    assignedAvatar: "ON",
    notes: "Betaler månedlig. Fornøyd med systemet.",
    addedDate: "2023-12-01",
  },
  {
    ...mockCompanies[6],
    status: "Kontaktet - ikke svar",
    lastContacted: "2024-01-17",
    assignedTo: "Per Olsen",
    assignedAvatar: "PO",
    notes: "Ringt 2 ganger. Send oppfølgingsepost.",
    addedDate: "2024-01-12",
  },
  {
    ...mockCompanies[1],
    status: "Ikke kontaktet",
    lastContacted: null,
    assignedTo: "Kari Hansen",
    assignedAvatar: "KH",
    notes: "",
    addedDate: "2024-01-19",
  },
  {
    ...mockCompanies[7],
    status: "Avslått",
    lastContacted: "2024-01-14",
    assignedTo: "Per Olsen",
    assignedAvatar: "PO",
    notes: "Ikke interessert akkurat nå. Prøv igjen om 6 måneder.",
    addedDate: "2024-01-05",
  },
  {
    ...mockCompanies[3],
    status: "Kontaktet",
    lastContacted: "2024-01-19",
    assignedTo: "Ola Nordmann",
    assignedAvatar: "ON",
    notes: "Demonstrasjon planlagt. Venter på svar.",
    addedDate: "2024-01-11",
  },
  {
    ...mockCompanies[9],
    status: "Booket møte",
    lastContacted: "2024-01-21",
    assignedTo: "Kari Hansen",
    assignedAvatar: "KH",
    notes: "Videomøte via Teams kl 14:00 i morgen.",
    addedDate: "2024-01-15",
  },
  {
    ...mockCompanies[10],
    status: "Ikke kontaktet",
    lastContacted: null,
    assignedTo: "Per Olsen",
    assignedAvatar: "PO",
    notes: "",
    addedDate: "2024-01-22",
  },
  {
    ...mockCompanies[11],
    status: "Kunde",
    lastContacted: "2024-01-20",
    assignedTo: "Ola Nordmann",
    assignedAvatar: "ON",
    notes: "Abonnerer på Pro-pakken. 45 ansatte.",
    addedDate: "2023-11-15",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    company: "Bergheim Regnskap AS",
    message: "Du ringte Bergheim Regnskap AS i går – ingen svar. Følg opp i dag?",
    date: "2024-01-22",
    type: "follow-up",
    done: false,
  },
  {
    id: "2",
    company: "Trondheim IT Konsulent AS",
    message: "Møte med Trondheim IT Konsulent AS i morgen kl 10:00. Forbered presentasjon.",
    date: "2024-01-23",
    type: "meeting",
    done: false,
  },
  {
    id: "3",
    company: "Hansen & Co Advokater",
    message: "Hansen & Co Advokater har ikke svart på e-post sendt for 3 dager siden. Tid for oppfølging?",
    date: "2024-01-20",
    type: "follow-up",
    done: false,
  },
  {
    id: "4",
    company: "Oslo Frisørsalong",
    message: "Planlagt oppfølging av Oslo Frisørsalong – det er 2 uker siden siste kontakt.",
    date: "2024-01-18",
    type: "reminder",
    done: false,
  },
  {
    id: "5",
    company: "Kristiansen Reklamebyrå",
    message: "Kristiansen Reklamebyrå ba om tilbud. Har du sendt det?",
    date: "2024-01-21",
    type: "follow-up",
    done: true,
  },
  {
    id: "6",
    company: "Stavanger Eiendom AS",
    message: "Kontrakt med Stavanger Eiendom AS signert. Husk onboarding-samtale.",
    date: "2024-01-22",
    type: "reminder",
    done: false,
  },
];

export const industries = [
  "Alle bransjer",
  "Regnskap",
  "Frisør",
  "Bygg",
  "IT og teknologi",
  "Eiendom",
  "Transport og logistikk",
  "Juridiske tjenester",
  "Elektro",
  "Fiskeri og havbruk",
  "Markedsføring",
  "Helse og omsorg",
  "Matservering",
];

export const norwegianCities = [
  "Oslo",
  "Bergen",
  "Trondheim",
  "Stavanger",
  "Molde",
  "Ålesund",
  "Kristiansand",
  "Tromsø",
  "Drammen",
  "Fredrikstad",
  "Sandnes",
  "Sarpsborg",
  "Bodø",
  "Sandefjord",
];
